CREATE TABLE [dbo].[Employee](
    [Emp_ID] [int] NOT NULL,
    [Emp_Name] [nvarchar](50) NOT NULL,
    [Emp_Salary] [int] NOT NULL,
    [Emp_City] [nvarchar](50) NOT NULL,
    CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED
    (
        [Emp_ID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

--====================================================================================================================================================

INSERT INTO Employee
SELECT 1, 'Ravi', 25000, 'Hyd' UNION ALL
SELECT 2, 'Rahul', 26000, 'Hyd' UNION ALL
SELECT 3, 'Sandeep', 25000, 'Hyd' UNION ALL
SELECT 4, 'Sanjeev', 24000, 'Hyd' UNION ALL
SELECT 5, 'Honey', 28000, 'Hyd' UNION ALL
SELECT 6, 'Sai', 20000, 'Hyd' UNION ALL
SELECT 7, 'Jaanu', 23000, 'Hyd';
--====================================================================================================================================================
--Example 1

SET NOCOUNT ON;
DECLARE @EMP_ID INT;
DECLARE @EMP_NAME NVARCHAR(MAX);
DECLARE @EMP_SALARY INT;
DECLARE @EMP_CITY NVARCHAR(MAX);

DECLARE EMP_CURSOR CURSOR
    LOCAL FORWARD_ONLY FOR
    SELECT * FROM Employee;
OPEN EMP_CURSOR;
FETCH NEXT FROM EMP_CURSOR INTO @EMP_ID, @EMP_NAME, @EMP_SALARY, @EMP_CITY;

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT 'EMP_ID: ' + CONVERT(NVARCHAR(MAX), @EMP_ID) + '  EMP_NAME ' + @EMP_NAME + '  EMP_SALARY ' + CONVERT(NVARCHAR(MAX), @EMP_SALARY) + '  EMP_CITY ' + @EMP_CITY;
    FETCH NEXT FROM EMP_CURSOR INTO @EMP_ID, @EMP_NAME, @EMP_SALARY, @EMP_CITY;
END;

CLOSE EMP_CURSOR;
DEALLOCATE EMP_CURSOR;
--=======================================================================================================================================================
-- Example 2 (SCROLL)

SET NOCOUNT ON
DECLARE @EMP_ID INT
DECLARE @EMP_NAME NVARCHAR(MAX)
DECLARE @EMP_SALARY INT
DECLARE @EMP_CITY NVARCHAR(MAX)

DECLARE EMP_CURSOR CURSOR
LOCAL  SCROLL  FOR
SELECT * FROM Employee
OPEN EMP_CURSOR
FETCH NEXT FROM EMP_CURSOR INTO  @EMP_ID ,@EMP_NAME,@EMP_SALARY,@EMP_CITY

FETCH RELATIVE 3 FROM EMP_CURSOR INTO  @EMP_ID ,@EMP_NAME,@EMP_SALARY,@EMP_CITY
PRINT  'EMP_ID: ' + CONVERT(NVARCHAR(MAX),@EMP_ID)+  '  EMP_NAME '+@EMP_NAME+'  EMP_SALARY '  +CONVERT(NVARCHAR(MAX),@EMP_SALARY)  +  '  EMP_CITY ' +@EMP_CITY
FETCH ABSOLUTE  3 FROM EMP_CURSOR INTO  @EMP_ID ,@EMP_NAME,@EMP_SALARY,@EMP_CITY

PRINT  'EMP_ID: ' + CONVERT(NVARCHAR(MAX),@EMP_ID)+  '  EMP_NAME '+@EMP_NAME+'  EMP_SALARY '  +CONVERT(NVARCHAR(MAX),@EMP_SALARY)  +  '  EMP_CITY ' +@EMP_CITY
FETCH FIRST FROM EMP_CURSOR INTO  @EMP_ID ,@EMP_NAME,@EMP_SALARY,@EMP_CITY
PRINT  'EMP_ID: ' + CONVERT(NVARCHAR(MAX),@EMP_ID)+  '  EMP_NAME '+@EMP_NAME+'  EMP_SALARY '  +CONVERT(NVARCHAR(MAX),@EMP_SALARY)  +  '  EMP_CITY ' +@EMP_CITY
FETCH LAST FROM EMP_CURSOR INTO  @EMP_ID ,@EMP_NAME,@EMP_SALARY,@EMP_CITY
PRINT  'EMP_ID: ' + CONVERT(NVARCHAR(MAX),@EMP_ID)+  '  EMP_NAME '+@EMP_NAME+'  EMP_SALARY '  +CONVERT(NVARCHAR(MAX),@EMP_SALARY)  +  '  EMP_CITY ' +@EMP_CITY
FETCH PRIOR FROM EMP_CURSOR INTO  @EMP_ID ,@EMP_NAME,@EMP_SALARY,@EMP_CITY
PRINT  'EMP_ID: ' + CONVERT(NVARCHAR(MAX),@EMP_ID)+  '  EMP_NAME '+@EMP_NAME+'  EMP_SALARY '  +CONVERT(NVARCHAR(MAX),@EMP_SALARY)  +  '  EMP_CITY ' +@EMP_CITY
FETCH NEXT FROM EMP_CURSOR INTO  @EMP_ID ,@EMP_NAME,@EMP_SALARY,@EMP_CITY
PRINT  'EMP_ID: ' + CONVERT(NVARCHAR(MAX),@EMP_ID)+  '  EMP_NAME '+@EMP_NAME+'  EMP_SALARY '  +CONVERT(NVARCHAR(MAX),@EMP_SALARY)  +  '  EMP_CITY ' +@EMP_CITY


CLOSE EMP_CURSOR
DEALLOCATE EMP_CURSOR
--=======================================================================================================================================================
--Example 3 (STATIC CURSOR)

SET NOCOUNT ON;
DECLARE @EMP_ID INT;
DECLARE @EMP_NAME NVARCHAR(MAX);
DECLARE @EMP_SALARY INT;
DECLARE @EMP_CITY NVARCHAR(MAX);

DECLARE EMP_CURSOR CURSOR STATIC FOR
SELECT * FROM Employee;

OPEN EMP_CURSOR;
FETCH NEXT FROM EMP_CURSOR INTO @EMP_ID, @EMP_NAME, @EMP_SALARY, @EMP_CITY;

WHILE @@FETCH_STATUS = 0
BEGIN
    IF @EMP_ID % 2 = 0
    BEGIN
        PRINT 'EMP_ID: ' + CONVERT(NVARCHAR(MAX), @EMP_ID) + '  EMP_NAME ' + @EMP_NAME + '  EMP_SALARY ' + CONVERT(NVARCHAR(MAX), @EMP_SALARY) + '  EMP_CITY ' + @EMP_CITY;
    END
    FETCH FROM EMP_CURSOR INTO @EMP_ID, @EMP_NAME, @EMP_SALARY, @EMP_CITY;
END

CLOSE EMP_CURSOR;
DEALLOCATE EMP_CURSOR;
--========================================================================================================================================================
--Example 4

SET NOCOUNT ON;
DECLARE @EMP_ID INT;
DECLARE @EMP_NAME NVARCHAR(MAX);
DECLARE @EMP_SALARY INT;
DECLARE @EMP_CITY NVARCHAR(MAX);

DECLARE EMP_CURSOR CURSOR STATIC FOR
SELECT * FROM Employee;

OPEN EMP_CURSOR;
FETCH NEXT FROM EMP_CURSOR INTO @EMP_ID, @EMP_NAME, @EMP_SALARY, @EMP_CITY;

WHILE @@FETCH_STATUS = 0
BEGIN
    IF @EMP_ID % 2 = 0
    BEGIN
        UPDATE Employee SET Emp_Salary = 15000 WHERE CURRENT OF EMP_CURSOR;
    END

    FETCH FROM EMP_CURSOR INTO @EMP_ID, @EMP_NAME, @EMP_SALARY, @EMP_CITY;
END

CLOSE EMP_CURSOR;
DEALLOCATE EMP_CURSOR;
--======================================================================================================================================================
--Example 5 (DYNAMIC CURSOR)

SET NOCOUNT ON;
DECLARE @EMP_ID INT;
DECLARE @EMP_NAME NVARCHAR(MAX);
DECLARE @EMP_SALARY INT;
DECLARE @EMP_CITY NVARCHAR(MAX);

DECLARE EMP_CURSOR CURSOR DYNAMIC FOR
SELECT * FROM Employee;

OPEN EMP_CURSOR;
FETCH NEXT FROM EMP_CURSOR INTO @EMP_ID, @EMP_NAME, @EMP_SALARY, @EMP_CITY;

WHILE @@FETCH_STATUS = 0
BEGIN
    IF @EMP_ID % 2 = 0
    BEGIN
        UPDATE Employee SET Emp_Salary = 15000 WHERE CURRENT OF EMP_CURSOR;
    END

    FETCH FROM EMP_CURSOR INTO @EMP_ID, @EMP_NAME, @EMP_SALARY, @EMP_CITY;
END

CLOSE EMP_CURSOR;
DEALLOCATE EMP_CURSOR;

SELECT * FROM Employee;
--========================================================================================================================================================
--Example 6

SET NOCOUNT ON;
DECLARE @EMP_ID INT;
DECLARE @EMP_NAME NVARCHAR(MAX);
DECLARE @EMP_SALARY INT;
DECLARE @EMP_CITY NVARCHAR(MAX);

DECLARE EMP_CURSOR CURSOR FAST_FORWARD FOR
    SELECT * FROM Employee;

OPEN EMP_CURSOR;
FETCH NEXT FROM EMP_CURSOR INTO @EMP_ID, @EMP_NAME, @EMP_SALARY, @EMP_CITY;

WHILE @@FETCH_STATUS = 0
BEGIN
    IF @EMP_ID % 2 = 0
    BEGIN
        UPDATE Employee SET Emp_Salary = 15000 WHERE CURRENT OF EMP_CURSOR;
    END;

    FETCH FROM EMP_CURSOR INTO @EMP_ID, @EMP_NAME, @EMP_SALARY, @EMP_CITY;
END;

CLOSE EMP_CURSOR;
DEALLOCATE EMP_CURSOR;
--==========================================================================================================================================================
--Example 7

SET NOCOUNT ON;
DECLARE @EMP_ID INT;
DECLARE @EMP_NAME NVARCHAR(MAX);
DECLARE @EMP_SALARY INT;
DECLARE @EMP_CITY NVARCHAR(MAX);

DECLARE EMP_CURSOR1 CURSOR KEYSET scroll FOR
    SELECT EMP_ID, EMP_NAME, EMP_SALARY, EMP_CITY FROM Employee order by Emp_Id;

OPEN EMP_CURSOR1;

IF @@CURSOR_ROWS > 0
BEGIN
    FETCH NEXT FROM EMP_CURSOR1 INTO @EMP_ID, @EMP_NAME, @EMP_SALARY, @EMP_CITY;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        If @EMP_ID % 2 = 0
            UPDATE Employee SET EMP_NAME = 'PANKAJ KUMAR CHOUDHARY' WHERE CURRENT OF EMP_CURSOR1;

        FETCH NEXT FROM EMP_CURSOR1 INTO @EMP_ID, @EMP_NAME, @EMP_SALARY, @EMP_CITY;
    END
END

CLOSE EMP_CURSOR1;
DEALLOCATE EMP_CURSOR1;

SET NOCOUNT OFF;

SELECT * FROM Employee;